### ISSUE TITLE
[BUG] 1.0.3 sequencesToPublishAsAccessoriesSwitch switches don't do anything

### ISSUE THREAD

**Issue by mxwlsavard** [nicoduj/homebridge-harmony#165]
**Describe the bug**
Switches published from sequencesToPublishAsAccessoriesSwitch don't activate sequences after I upgraded from 0.7.0 -> 1.0.3. They switch on when activated then switch off a split second later, which seems like expected behavior. My switchAccessories switches do work. I have double checked that I have the right activity active for the sequences.

**To Reproduce**
1. Have a sequence defined in a Harmony activity.
2. Activate Harmony activity.
3. Activate HomeKit switch for the sequence.
4. Watch nothing happen ;)

**Expected behavior**
The specified sequence should execute.

**IOS (please complete the following information):**
I tried this on an iPhone XS on iOS 13 public beta 6 and a MacBook on Mojave 

**Logs**
I've included what I suspect are the relevant logs. If you need more just let me know.
> [8/17/2019, 10:52:17 PM] [HarmonyHub] INFO - sendingCommand{"sequenceId":"undefined"}
[8/17/2019, 10:52:17 PM] [HarmonyHub] INFO - sendCommand done{"cmd":"vnd.logitech.harmony/vnd.logitech.harmony.engine?sequenceFinished","code":563,"id":"0.13815475846427616","msg":"undefined: Sequene not found"}

**Config**
My config:
```
            "platform": "HarmonyHubWebSocket",
            "name": "HarmonyHub",
            "hubIP": "192.168.0.101",
            "switchAccessories": true,
            "showTurnOffActivity": false,
            "mainActivity": "TV",
            "sequencesToPublishAsAccessoriesSwitch": [
                "A and E",
                "Dim TV",
                "Bright TV",
                "Comedy Central"
            ]
```

**Comment by nicoduj** [comment]
Hi, From the log I see it does not retrieve the sequence is in your hub config . Maybe the name in the list are not the one in your hub config ? Your hub config, shown at the beginning of the log should telle is if it is the case or if there is a real bug. Will try to reproduce if it is the case . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Ok, i didn’t see the beginning of the log on githawk but it was there in the mail : the names seems ok will check thank you for reporting

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nicoduj** [comment]
Found it, have to change line 433 of harmonybase.js from :  service.***S***equenceId to  service.***s***equenceId ... will fix and release ASAP sorry for that regression . 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mxwlsavard** [comment]
No worries! Thanks for looking into it!
